# Generated by Django 5.0.1 on 2025-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('all', 'All'), ('guardian', 'Guardians'), ('student', 'Students'), ('teacher', 'Teachers')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.CheckConstraint(check=models.Q(('total_fee__gte', 0)), name='positive_total_fee'),
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.CheckConstraint(check=models.Q(('total_paid__gte', 0)), name='positive_total_paid'),
        ),
    ]
