# Generated by Django 5.0.1 on 2025-04-06 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectresult',
            name='assignment',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='continuous_assessment_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='continuous_assessment_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='continuous_assessment_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(40.0)]),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='oral_test',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(20.0)]),
        ),
    ]
