# Generated by Django 5.0.1 on 2024-11-21 03:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 4, 12, 48, 832623)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 4, 12, 48, 832623)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(default=None, related_name='subjects_set', to='core.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(default=None, related_name='subjects', to='core.student'),
        ),
        migrations.CreateModel(
            name='AcademicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('assignment', 'Assignment'), ('assessment', 'Assessment'), ('exam', 'Exam')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('total_grade', models.FloatField(blank=True, null=True)),
                ('related_object_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_alerts', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='core.teacher')),
            ],
        ),
    ]
