# Generated by Django 5.0.1 on 2025-04-11 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subjectresult_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['term__start_date', 'student__user__last_name']},
        ),
        migrations.RemoveConstraint(
            model_name='financialrecord',
            name='positive_total_fee',
        ),
        migrations.RemoveConstraint(
            model_name='financialrecord',
            name='positive_total_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='term',
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.student'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.term'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='financial_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.financialrecord'),
        ),
        migrations.AlterField(
            model_name='studentfeerecord',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfeerecord',
            name='net_fee',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfeerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='core.student'),
        ),
        migrations.AlterField(
            model_name='studentfeerecord',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_records', to='core.term'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfeerecord',
            unique_together={('student', 'term', 'fee_assignment')},
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.CheckConstraint(check=models.Q(('total_fee__gte', 0)), name='financial_record_positive_total_fee'),
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.CheckConstraint(check=models.Q(('total_discount__gte', 0)), name='financial_record_positive_total_discount'),
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.CheckConstraint(check=models.Q(('total_paid__gte', 0)), name='financial_record_positive_total_paid'),
        ),
    ]
