# Generated by Django 5.0.1 on 2025-04-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_financialrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolday',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='schoolday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolday',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_days', to='core.term'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolday',
            unique_together={('term', 'date')},
        ),
    ]
