# Generated by Django 5.0.1 on 2025-04-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_term_options_alter_term_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
    ]
