# Generated by Django 5.0.1 on 2024-11-23 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='promotion_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('left', 'Left School')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 1, 49, 26, 460003)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 1, 49, 26, 460003)),
        ),
    ]
