# Generated by Django 5.0.1 on 2025-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
