# Generated by Django 5.0.1 on 2025-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_class_description_alter_class_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
