# Generated by Django 5.0.1 on 2025-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_term_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['session__start_date', 'order']},
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
