# Generated by Django 5.0.1 on 2024-11-23 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 2, 35, 34, 972517)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 2, 35, 34, 972517)),
        ),
        migrations.AlterField(
            model_name='class',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
