# Generated by Django 5.0.1 on 2024-11-25 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('left', 'Left School')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('left', 'Left School')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 23, 29, 22, 971606)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 23, 29, 22, 971606)),
        ),
    ]
