# Generated by Django 5.0.1 on 2025-06-18 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicalert',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts_by_teacher', to='core.teacher'),
        ),
    ]
