# Generated by Django 5.0.1 on 2025-06-18 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_academicalert_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicalert',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='academicalert',
            name='teacher',
        ),
        migrations.AddField(
            model_name='academicalert',
            name='source_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_academic_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
