# Generated by Django 5.0.1 on 2024-12-02 13:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_message_title_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 14, 57, 59, 609083)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 14, 57, 59, 609083)),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.student'),
        ),
    ]
