# Generated by Django 5.0.1 on 2025-06-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_academicalert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicalert',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicalert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicalert',
            name='alert_type',
            field=models.CharField(choices=[('assignment_available', 'Assignment Available'), ('assignment_submission', 'Assignment Submitted'), ('assessment_available', 'Assessment Available'), ('assessment_submission', 'Assessment Submitted'), ('exam_available', 'Exam Available'), ('exam_submission', 'Exam Submitted'), ('general_announcement', 'General Announcement')], max_length=30),
        ),
    ]
