# Generated by Django 5.0.1 on 2025-06-22 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_academicalert_duration_academicalert_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_for_assessment', to='core.assessment'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_for_exam', to='core.exam'),
        ),
    ]
