# Generated by Django 5.0.1 on 2025-06-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_assessmentsubmission_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Total marks possible for this assessment.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, help_text='Total marks possible for this assessment.', null=True),
        ),
        migrations.AddField(
            model_name='onlinequestion',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
