# Generated by Django 5.0.1 on 2025-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalresult',
            name='performance_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionalresult',
            name='subject_summary_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
