# Generated by Django 5.0.1 on 2024-12-31 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_assessment_approved_by_assessment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 23, 4, 54, 616614)),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 23, 4, 54, 616614)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 23, 4, 54, 616614)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 23, 4, 54, 616614)),
        ),
    ]
