# Generated by Django 5.0.1 on 2025-08-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sessionalresult_performance_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumulativerecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cumulative_record', serialize=False, to='core.student'),
        ),
    ]
