# Generated by Django 5.0.1 on 2024-12-31 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_assessment_created_at_assessment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 8, 16, 882975)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 8, 16, 882975)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 8, 16, 867349)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 8, 16, 867349)),
        ),
    ]
