# Generated by Django 5.0.1 on 2025-01-01 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_class',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 3, 50, 51, 570482)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 3, 50, 51, 570482)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 3, 50, 51, 567484)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 3, 50, 51, 567484)),
        ),
    ]
