# Generated by Django 5.0.1 on 2025-10-03 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_assessment_result_field_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_online',
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, help_text='The attempt number for this submission.', validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, help_text='The attempt number for this submission.', validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('student', 'assessment', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('student', 'exam', 'attempt_number')},
        ),
    ]
