# Generated by Django 5.0.1 on 2025-10-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_assessment_is_online_remove_exam_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinequestion',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
