# Generated by Django 5.0.1 on 2025-01-03 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_class_teacher_remove_teacher_current_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='date',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 3, 40, 0, 505770)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 3, 40, 0, 505770)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 3, 40, 0, 502772)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 3, 40, 0, 502772)),
        ),
    ]
