# Generated by Django 5.0.1 on 2025-10-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_exam_result_field_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
