# Generated by Django 5.0.1 on 2025-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_assessmentsubmission_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='profile_image',
            field=models.ImageField(blank=True, default='core/images/default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='core/images/default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, default='core/images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
