# Generated by Django 5.0.1 on 2026-01-03 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_guardian_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('attendance_marked', 'Marked Attendance'), ('assessment_created', 'Created Assessment'), ('exam_created', 'Created Exam'), ('assignment_created', 'Created Assignment'), ('score_uploaded', 'Uploaded Student Scores'), ('result_approved', 'Approved Results'), ('course_created', 'Created LMS Course'), ('course_updated', 'Updated LMS Course'), ('content_uploaded', 'Uploaded Course Content'), ('guardian_login', 'Guardian Logged In'), ('view_student_results', 'Viewed Student Results'), ('view_attendance', 'Viewed Attendance'), ('view_fees', 'Viewed Fee Records'), ('message_sent', 'Sent Message'), ('payment_made', 'Made Payment'), ('student_login', 'Student Logged In'), ('assignment_submitted', 'Submitted Assignment'), ('assessment_submitted', 'Submitted Assessment'), ('exam_submitted', 'Submitted Exam'), ('course_viewed', 'Viewed Course'), ('course_enrolled', 'Enrolled in Course'), ('lesson_completed', 'Completed Lesson'), ('result_viewed', 'Viewed Results'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('profile_updated', 'Updated Profile')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('related_model', models.CharField(blank=True, help_text="Model name (e.g., 'Assessment', 'Attendance')", max_length=100)),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'user'], name='core_activi_created_1503ae_idx'), models.Index(fields=['activity_type', '-created_at'], name='core_activi_activit_84f18c_idx'), models.Index(fields=['user', 'activity_type'], name='core_activi_user_id_fc76d8_idx')],
            },
        ),
    ]
