# Generated by Django 5.0.1 on 2026-01-05 16:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_guardian_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='LearnSwift Academia', max_length=200)),
                ('school_motto', models.CharField(blank=True, default='Excellence in Education', max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='system/')),
                ('school_address', models.TextField(blank=True)),
                ('school_phone', models.CharField(blank=True, max_length=20)),
                ('school_email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('school_website', models.URLField(blank=True)),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=100)),
                ('email_port', models.IntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.EmailField(blank=True, max_length=254)),
                ('email_host_password', models.CharField(blank=True, help_text='Stored encrypted', max_length=200)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('grading_system', models.JSONField(blank=True, default=dict, help_text='Grading scale configuration: {grade: {min_score, max_score, remark}}')),
                ('passing_grade', models.IntegerField(default=40, help_text='Minimum score to pass', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attendance_threshold', models.IntegerField(default=75, help_text='Minimum attendance percentage required (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('late_arrival_grace_period', models.IntegerField(default=15, help_text='Grace period for late arrival in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('enable_fee_module', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='NGN', max_length=10)),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('late_payment_penalty_enabled', models.BooleanField(default=False)),
                ('late_payment_penalty_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enable_assignments', models.BooleanField(default=True)),
                ('enable_assessments', models.BooleanField(default=True)),
                ('enable_exams', models.BooleanField(default=True)),
                ('assignment_max_score', models.IntegerField(default=10)),
                ('assessment_max_score', models.IntegerField(default=20)),
                ('exam_max_score', models.IntegerField(default=70)),
                ('show_position', models.BooleanField(default=True, help_text='Show class position on results')),
                ('auto_promote_students', models.BooleanField(default=False, help_text='Automatically promote students at end of session')),
                ('result_approval_required', models.BooleanField(default=True, help_text='Require admin approval before publishing results')),
                ('default_term_duration_weeks', models.IntegerField(default=12, help_text='Default duration for a term in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('number_of_terms_per_session', models.IntegerField(default=3, help_text='Number of terms in an academic session', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('academic_year_start_month', models.IntegerField(default=9, help_text='Month when academic year begins (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('enable_lms', models.BooleanField(default=True, help_text='Enable Learning Management System')),
                ('enable_blog', models.BooleanField(default=True, help_text='Enable blog/news feature')),
                ('enable_messaging', models.BooleanField(default=True, help_text='Enable internal messaging')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('sms_provider', models.CharField(blank=True, choices=[('twilio', 'Twilio'), ('africastalking', "Africa's Talking"), ('custom', 'Custom')], default='twilio', max_length=50)),
                ('sms_api_key', models.CharField(blank=True, help_text='SMS provider API key', max_length=200)),
                ('sms_sender_id', models.CharField(blank=True, help_text='SMS sender name/number', max_length=20)),
                ('enable_online_payment', models.BooleanField(default=False, help_text='Enable online fee payment')),
                ('payment_provider', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe')], default='paystack', max_length=50)),
                ('payment_public_key', models.CharField(blank=True, max_length=200)),
                ('payment_secret_key', models.CharField(blank=True, help_text='Stored encrypted', max_length=200)),
                ('payment_test_mode', models.BooleanField(default=True, help_text='Use test mode for payments')),
                ('enable_online_admission', models.BooleanField(default=False, help_text='Enable online student admission')),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('require_admission_approval', models.BooleanField(default=True, help_text='Require admin approval for admissions')),
                ('max_students_per_class', models.IntegerField(default=40, help_text='Maximum number of students allowed per class', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('report_card_header', models.TextField(blank=True, help_text='Custom header text for report cards')),
                ('report_card_footer', models.TextField(blank=True, help_text='Custom footer text for report cards')),
                ('principal_signature', models.ImageField(blank=True, null=True, upload_to='system/signatures/')),
                ('show_student_photo_on_report', models.BooleanField(default=True)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('backup_frequency_days', models.IntegerField(default=7, help_text='Number of days between automatic backups', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put system in maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default='System is under maintenance. Please check back later.')),
                ('require_email_verification', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=60, help_text='Auto-logout after inactivity (minutes)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('max_login_attempts', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
