# Generated by Django 5.0.1 on 2026-01-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary Education'), ('SSCE', 'SSCE/WAEC/NECO'), ('OND', 'Ordinary National Diploma (OND)'), ('NCE', 'Nigeria Certificate in Education (NCE)'), ('HND', 'Higher National Diploma (HND)'), ('BSc', "Bachelor's Degree"), ('PGD', 'Postgraduate Diploma (PGD)'), ('MSc', "Master's Degree"), ('PhD', 'Doctorate (PhD)'), ('None', 'No Formal Education'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Highest Educational Qualification'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='ndpr_consent',
            field=models.BooleanField(default=False, verbose_name='NDPR Consent'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='ndpr_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consent Date'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='National Identification Number'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='student',
            name='ndpr_consent',
            field=models.BooleanField(default=False, verbose_name='NDPR Consent (Guardian)'),
        ),
        migrations.AddField(
            model_name='student',
            name='ndpr_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consent Date'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('SSCE', 'SSCE/WAEC/NECO'), ('OND', 'Ordinary National Diploma (OND)'), ('NCE', 'Nigeria Certificate in Education (NCE)'), ('HND', 'Higher National Diploma (HND)'), ('BSc', "Bachelor's Degree (BSc/BA/BEd)"), ('PGD', 'Postgraduate Diploma (PGD)'), ('MSc', "Master's Degree (MSc/MA/MEd)"), ('PhD', 'Doctorate (PhD)'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Highest Educational Qualification'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ndpr_consent',
            field=models.BooleanField(default=False, verbose_name='NDPR Consent'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ndpr_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consent Date'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='National Identification Number'),
        ),
    ]
