# Generated by Django 5.0.1 on 2025-09-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsalms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='is_active',
        ),
    ]
