# Generated by Django 5.0.1 on 2025-09-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lsalms', '0002_remove_courseenrollment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grading_weights',
        ),
        migrations.CreateModel(
            name='GradedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(default=10, help_text='The percentage weight of this activity in the final course grade (e.g., 20 for 20%).')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_activities', to='lsalms.course')),
            ],
            options={
                'unique_together': {('course', 'content_type', 'object_id')},
            },
        ),
    ]
