# Generated by Django 5.0.1 on 2025-09-07 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cumulativerecord_student'),
        ('lsalms', '0003_remove_course_grading_weights_gradedactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title', 'subject__name']},
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_internal_course_per_class_term',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('course_type', 'INTERNAL')), fields=('linked_class', 'term', 'subject'), name='unique_subject_course_per_class_term'),
        ),
    ]
