# Generated by Django 5.0.1 on 2025-09-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsalms', '0004_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedactivity',
            name='max_score',
            field=models.PositiveIntegerField(default=100, help_text='The maximum possible score for this activity (e.g., 50 marks).'),
        ),
    ]
