# Generated by Django 5.0.1 on 2025-10-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsalms', '0005_gradedactivity_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a course thumbnail image. Recommended size: 800x600.', null=True, upload_to='courses/thumbnails/'),
        ),
    ]
